//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadIdan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attractions
    {
        public int Id { get; set; }
        public int AttractionID { get; set; }
        public string AttractionName { get; set; }
        public int LocationID { get; set; }
        public System.DateTime AttractionDate { get; set; }
        public decimal AttractionPrice { get; set; }
        public decimal Price { get; set; }
        public int SiteID { get; set; }
        public string AttractionSiteUrl { get; set; }
        public string AttractionData1 { get; set; }
        public string AttractionData2 { get; set; }
        public Nullable<int> AttractionTypeID { get; set; }
        public Nullable<int> AttractionTypeValue { get; set; }
        public string AttractionImage { get; set; }
    
        public virtual AttractionTypes AttractionTypes { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Sites Sites { get; set; }
    }
}
